routes/web.php
<?php

use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SystemConfigurationController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home'); 

    Route::get(
        'categories/{category}/delete',
        [App\Http\Controllers\CategoryController::class,
            'delete'
        ])->name('categories.delete');
    Route::resource('categories', App\Http\Controllers\CategoryController::class);

    Route::get(
        'clients/{client}/delete',
        [App\Http\Controllers\ClientController::class,
            'delete'
        ])->name('clients.delete');
    Route::resource('clients', App\Http\Controllers\ClientController::class);

    Route::get(
        'users/{user}/delete',
        [App\Http\Controllers\UserController::class,
            'delete'
        ])->name('users.delete');
    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get(
        'products/{product}/delete',
        [App\Http\Controllers\ProductController::class,
            'delete'
        ])->name('products.delete');
    Route::resource('products', ProductController::class);

    Route::resource('orders', OrderController::class);
    Route::get('pdv', [OrderController::class, 'create']);

    Route::get(
        'suppliers/{supplier}/delete',
        [App\Http\Controllers\SupplierController::class,
            'delete'
        ])->name('suppliers.delete');
    Route::resource('suppliers', App\Http\Controllers\SupplierController::class);

    Route::prefix('configurations')->name('configurations.')->group(function () {
        Route::get('system', [SystemConfigurationController::class, 'edit'])->name('system.edit');
        Route::put('system', [SystemConfigurationController::class, 'update'])->name('system.update');
    });
});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Traits\MaskValueTrait;

class Client extends Model
{
    use HasFactory, SoftDeletes, MaskValueTrait;

    protected $fillable = [
        'full_name',
        'social_name',
        'gender',
        'photo_url',
        'cpf',
        'rg',
        'birthdate',
        'cellphone',
        'phone',
        'email',
        'observation',
        'profession',
        'is_active'
    ];

    public function address()
    {
        return $this->morphOne(Address::class, 'owner');
    }

    public function getCpfAttribute($value)
    {
        return $this->mask($value, '###.###.###-##');
    }

    public function getCellphoneAttribute($value)
    {
        return $this->mask($value, '(##) ####-####');
    }
}

app/Http/Controllers/ClientController.php
<?php

namespace App\Http\Controllers;

use App\Models\Client;
use App\Services\Client\DataTableClientService;
use App\Services\Client\IndexClientService;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ClientController extends Controller
{
    /**
     * @var IndexClientService
     */
    private $indexClientService;

    /**
     * ClientController constructor.
     * @param IndexClientService $indexClientService
     */
    public function __construct(IndexClientService $indexClientService)
    {
        $this->indexClientService = $indexClientService;
    }

    /**
     * @param Request $request
     * @return Application|Factory|View
     */
    public function index(Request $request, DataTableClientService $dataTableClientService)
    {
        if($request->ajax()) {
            return $dataTableClientService->run();
        }

        $search = null;
        if ($request->search) {
            $search = $request->search;
        }
        $clients = $this->indexClientService->run($request);

        if ($request->expectsJson()) {
            return response($clients);
        }

        return view('clients.index')
            ->with('clients', $clients)
            ->with('search', $search);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('clients.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $user = auth()->user();

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $fileName = time() . '.' . $photo->getClientOriginalExtension();
            $data['photo_url'] = $photo->storeAs('public/clients_photos', $fileName, 'local');
            $data['photo_url'] = str_replace('public/', '', $data['photo_url']);
        }

        $data['postcode'] = preg_replace('/[^0-9]/', '', $data['postcode']);
        $data['cpf'] = preg_replace('/[^0-9]/', '', $data['cpf']);
        $data['rg'] = preg_replace('/[^0-9]/', '', $data['rg']);
        $data['cellphone'] = preg_replace('/[^0-9]/', '', $data['cellphone']);
        $data['phone'] = preg_replace('/[^0-9]/', '', $data['phone']);
        $data['is_active'] = isset($data['is_active']) ? true : false;
        $newClient = new Client($data);

        $newClient->user_add_id = $user->id;
        $newClient->save();

        $newClient->address()->create($data);

        return redirect()->route('clients.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function edit($id)
    {
        $client = Client::findOrFail($id);

        return view('clients.edit', compact('client'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param int $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $client = Client::findOrFail($id);

        if ($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $fileName = time() . '.' . $photo->getClientOriginalExtension();
            $data['photo_url'] = $photo->storeAs('public/clients_photos', $fileName, 'local');
            $data['photo_url'] = str_replace('public/', '', $data['photo_url']);
        }

        $data['postcode'] = preg_replace('/[^0-9]/', '', $data['postcode']);
        $data['cpf'] = preg_replace('/[^0-9]/', '', $data['cpf']);
        $data['rg'] = preg_replace('/[^0-9]/', '', $data['rg']);
        $data['cellphone'] = preg_replace('/[^0-9]/', '', $data['cellphone']);
        $data['phone'] = preg_replace('/[^0-9]/', '', $data['phone']);
        $data['is_active'] = $data['is_active'] ? true : false;

        $client->update($data);

        $address = [
            'postcode' => $data['postcode'],
            'street' => $data['street'],
            'neighborhood' => $data['neighborhood'],
            'number' => $data['number'],
            'city' => $data['city'],
            'state' => $data['state'],
        ];

        $client->address()->update($address);

        return redirect()->route('clients.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     */
    public function delete($id)
    {

        $client = Client::findOrFail($id);

        return view('clients.delete', compact('client'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return Response
     */
    public function destroy($id)
    {
        Client::destroy($id);

        return redirect()->route('clients.index');
    }
}

resources/views/clients/create.blade.php
@extends('adminlte::page')

@section('title', 'Clientes')

@section('content_header')
    <h1>Clientes</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Cadastrar Novo Cliente</h3>
          </div>
          <form method="POST" enctype="multipart/form-data" action="/clients">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group">
                <label for="full_name">Nome</label>
                <input type="text" class="form-control" name="full_name" id="name">
              </div>
              <div class="form-group">
                <label for="social_name">Nome Social</label>
                <input type="text" class="form-control" name="social_name" id="social_name">
              </div>
              <div class="form-group">
                <label for="photo">Foto</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" name="photo" id="photo">
                  <label class="custom-file-label" for="photo">Selecione um arquivo</label>
                </div>
              </div>
              <div class="form-group">
                  <label for="email">E-mail</label>
                  <input type="email" class="form-control" name="email" id="email">
              </div>
              <div class="form-group">
                <label for="gender">Sexo</label>
                <select name="gender" id="gender" class="form-control">
                    <option value="f">Feminino</option>
                    <option value="m">Masculino</option>
                    <option value="o">Outro</option>
                    <option value="">Prefiro não dizer</option>
                </select>
              </div>
              <div class="form-group">
                  <label for="cpf">CPF</label>
                  <input data-inputmask="'mask': '999.999.999-99' "type="text" class="form-control" name="cpf" id="cpf">
              </div>
              <div class="form-group">
                  <label for="rg">RG</label>
                  <input  data-inputmask="'mask': '99.999.999-9'" type="text" class="form-control" name="rg" id="rg">
              </div>
              <div class="form-group">
                  <label for="birthdate">Data de Nascimeto</label>
                  <input type="date" class="form-control" name="birthdate" id="birthdate">
              </div>
              <div class="form-group">
                  <label for="cellphone">Celular</label>
                  <input data-inputmask="'mask': '(99) 9999-9999' "type="text" class="form-control" name="cellphone" id="cellphone">
              </div>
              <div class="form-group">
                  <label for="phone">Telefone</label>
                  <input data-inputmask="'mask': '(99) 99999-9999'" type="text" class="form-control" name="phone" id="phone">
              </div>
              <div class="form-group">
                  <label for="observation">Observação</label>
                  <input type="text" class="form-control" name="observation" id="observation">
              </div>
              <div class="form-group">
                  <label for="profession">Profissão</label>
                  <input type="text" class="form-control" name="profession" id="profession">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_active" name="is_active">
                <label class="form-check-label" for="is_active">Ativo</label>
              </div>
              <h5 class="mt-2">Endereço</h5>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="postcode">CEP</label>
                  <input data-inputmask="'mask': '99999-999'" type="text" class="form-control" name="postcode" id="postcode">
                </div>
                <div class="form-group col-md-6">
                  <label for="street">Rua/Av.</label>
                  <input type="text" class="form-control" name="street" id="street">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="neighborhood">Bairro</label>
                  <input type="text" class="form-control" name="neighborhood" id="neighborhood">
                </div>
                <div class="form-group col-md-3">
                  <label for="number">Numero</label>
                  <input type="text" class="form-control" name="number" id="number">
                </div>
                <div class="form-group col-md-3">
                  <label for="complement">Complemento (Opcional)</label>
                  <input type="text" class="form-control" name="complement" id="complement">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="city">Cidade</label>
                  <input type="text" class="form-control" name="city" id="city">
                </div>
                <div class="form-group col-md-6">
                    <label for="state">Estado</label>
                    <select name="state" id="state" class="form-control">
                        @include('utils.states')
                    </select>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                <a href="{{route('clients.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.bscustomfileinput', true)
@section('plugins.InputMask', true)

@section('js')
<script>
    $(document).ready(function () {
        bscustomfileinput.init();
    });

    $(":input").inputmask();
    $("#postcode").blur(function() {
         var postcode = $(this).val().replace(/\D/g, '');
         console.log(postcode)
        if (postcode.length === 8) {
            $("#street").val("...");
            $("#neighborhood").val("...");
            $("#city").val("...");
            $("#state").val("...");

            $.getJSON("https://viacep.com.br/ws/"+ postcode +"/json/?callback=?", function(data) {
                console.log(data)
                if (!("erro" in data)) {
                    $("#street").val(data.logradouro);
                    $("#neighborhood").val(data.bairro);
                    $("#city").val(data.localidade);
                    $("#state").val(data.uf);
                }
            });
        }
    });

</script>
@stop

resources/views/clients/delete.blade.php
@extends('adminlte::page')

@section('title', 'Clientes')

@section('content_header')
    <h1>Clientes</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Deletar Cliente - {{$client->full_name}}</h3>
          </div>
          <form method="POST" action="{{route('clients.destroy', ['client' => $client->id])}}">
            <!-- /.card-header -->
            <div class="card-body">
                Deseja realmente deletar o cliente - {{$client->full_name}}?
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                @method('delete')
                <a href="{{route('clients.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('js')
@stop

resources/views/clients/edit.blade.php
@extends('adminlte::page')

@section('title', 'Clientes')

@section('content_header')
    <h1>Clientes</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Editar cliente - {{$client->full_name}}</h3>
          </div>
          <form method="POST" action="{{route('clients.update', ['client' => $client->id])}}">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group">
                <label for="full_name">Nome</label>
                <input value="{{$client->full_name}}" type="text" class="form-control" name="full_name" id="name">
              </div>
              <div class="form-group">
                <label for="social_name">Nome Social</label>
                <input value="{{$client->social_name}}" type="text" class="form-control" name="social_name" id="social_name">
              </div>
              <div class="form-group">
                <label for="photo">Foto</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" name="photo" id="photo">
                  <label class="custom-file-label" for="photo">Selecione um arquivo</label>
                </div>
              </div>
              <div class="form-group">
                  <label for="email">E-mail</label>
                  <input value="{{$client->email}}" type="email" class="form-control" name="email" id="email">
              </div>
              <div class="form-group">
                <label for="gender">Sexo</label>
                <select name="gender" id="gender" class="form-control">
                    <option {{( $client->gender === 'f') ? 'selected' : '' }} value="f">Feminino</option>
                    <option {{( $client->gender === 'm') ? 'selected' : '' }} value="m">Masculino</option>
                    <option {{( $client->gender === 'o') ? 'selected' : '' }} value="o">Outro</option>
                    <option {{( $client->gender === '') ? 'selected' : '' }} value="">Prefiro não dizer</option>
                </select>
              </div>
              <div class="form-group">
                  <label for="cpf">CPF</label>
                  <input value="{{$client->cpf}}" data-inputmask="'mask': '999.999.999-99' "type="text" class="form-control" name="cpf" id="cpf">
              </div>
              <div class="form-group">
                  <label for="rg">RG</label>
                  <input value="{{$client->rg}}" data-inputmask="'mask': '99.999.999-9'" type="text" class="form-control" name="rg" id="rg">
              </div>
              <div class="form-group">
                  <label for="birthdate">Data de Nascimeto</label>
                  <input value="{{$client->birthdate}}" type="date" class="form-control" name="birthdate" id="birthdate">
              </div>
              <div class="form-group">
                  <label for="cellphone">Celular</label>
                  <input value="{{$client->cellphone}}" data-inputmask="'mask': '(99) 9999-9999' "type="text" class="form-control" name="cellphone" id="cellphone">
              </div>
              <div class="form-group">
                  <label for="phone">Telefone</label>
                  <input value="{{$client->phone}}" data-inputmask="'mask': '(99) 99999-9999'" type="text" class="form-control" name="phone" id="phone">
              </div>
              <div class="form-group">
                  <label for="observation">Observação</label>
                  <input value="{{$client->observation}}" type="text" class="form-control" name="observation" id="observation">
              </div>
              <div class="form-group">
                  <label for="profession">Profissão</label>
                  <input value="{{$client->profession}}" type="text" class="form-control" name="profession" id="profession">
              </div>
              <div class="form-check">
                <input checked="{{$client->is_active}}" type="checkbox" class="form-check-input" id="is_active" name="is_active">
                <label class="form-check-label" for="is_active">Ativo</label>
              </div>
              <h5 class="mt-2">Endereço</h5>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="postcode">CEP</label>
                  <input value="{{$client->address->postcode}}" data-inputmask="'mask': '99999-999'" type="text" class="form-control" name="postcode" id="postcode">
                </div>
                <div class="form-group col-md-6">
                  <label for="street">Rua/Av.</label>
                  <input value="{{$client->address->street}}" type="text" class="form-control" name="street" id="street">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="neighborhood">Bairro</label>
                  <input value="{{$client->address->neighborhood}}" type="text" class="form-control" name="neighborhood" id="neighborhood">
                </div>
                <div class="form-group col-md-3">
                  <label for="number">Numero</label>
                  <input value="{{$client->address->number}}" type="text" class="form-control" name="number" id="number">
                </div>
                <div class="form-group col-md-3">
                  <label for="complement">Complemento (Opcional)</label>
                  <input value="{{$client->address->complemet}}" type="text" class="form-control" name="complement" id="complement">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="city">Cidade</label>
                  <input value="{{$client->address->city}}" type="text" class="form-control" name="city" id="city">
                </div>
                <div class="form-group col-md-6">
                    <label for="state">Estado</label>
                    <select value="{{$client->address->state}}" name="state" id="state" class="form-control">
                        @include('utils.states')
                    </select>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                @method('put')
                <a href="{{route('clients.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Editar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.InputMask', true)

@section('js')
<script>
    $(":input").inputmask();
    $("#postcode").blur(function() {
         var postcode = $(this).val().replace(/\D/g, '');
         console.log(postcode)
        if (postcode.length === 8) {
            $("#street").val("...");
            $("#neighborhood").val("...");
            $("#city").val("...");
            $("#state").val("...");

            $.getJSON("https://viacep.com.br/ws/"+ postcode +"/json/?callback=?", function(data) {
                console.log(data)
                if (!("erro" in data)) {
                    $("#street").val(data.logradouro);
                    $("#neighborhood").val(data.bairro);
                    $("#city").val(data.localidade);
                    $("#state").val(data.uf);
                }
            });
        }
    });
</script>
@stop

resources/views/clients/index.blade.php
@extends('adminlte::page')

@section('title', 'Clientes')

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Lista de Clientes</h3>
            <div class="card-tools">
                <a href="{{route('clients.create')}}">Cadastrar Novo Cliente</a>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="clients" class="table table-bordered table-hover mb-2"  style="width:100%">
              <thead>
              <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>E-mail</th>
                <th>CPF</th>
                <th>Data de Nascimento</th>
                <th>Celular</th>
                <th>Status</th>
                <th>Total Compras</th>
                <th>Ações</th>
              </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.Datatables', true)

@section('js')
    <script>
        $( document ).ready(function() {
            console.log( "ready!" );
            $('#clients').DataTable({
            "paging": true,
            "lengthChange": false,
            "stripeClasses": [ 'bg-white', 'bg-light'],
            ajax: "{{ route('clients.index') }}",
            columns: [
                {data: 'id', name: 'id'},
                {data: 'client', name: 'name'},
                {data: 'email', name: 'email'},
                {data: 'cpf', name: 'CPF'},
                {data: 'birthdate', name: 'Data de Aniversário'},
                {data: 'cellphone', name: 'Celular'},
                {data: 'is_active', name: 'Status'},
                {data: 'total_purchases', name: 'Total Compras'},
                {data: 'action', name: 'Ações'},
            ],
            "searching": true,
            "language": {
                search: 'Pesquisar'
            },
            "ordering": true,
            "processing": true,
            "serverSide": true,
            "autoWidth": true,
            "responsive": true,
            "scrollX": true
            });
        });
    </script>
@stop