routes/web.php
<?php

use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SystemConfigurationController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home'); 

    Route::get(
        'categories/{category}/delete',
        [App\Http\Controllers\CategoryController::class,
            'delete'
        ])->name('categories.delete');
    Route::resource('categories', App\Http\Controllers\CategoryController::class);

    Route::get(
        'clients/{client}/delete',
        [App\Http\Controllers\ClientController::class,
            'delete'
        ])->name('clients.delete');
    Route::resource('clients', App\Http\Controllers\ClientController::class);

    Route::get(
        'users/{user}/delete',
        [App\Http\Controllers\UserController::class,
            'delete'
        ])->name('users.delete');
    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get(
        'products/{product}/delete',
        [App\Http\Controllers\ProductController::class,
            'delete'
        ])->name('products.delete');
    Route::resource('products', ProductController::class);

    Route::resource('orders', OrderController::class);
    Route::get('pdv', [OrderController::class, 'create']);

    Route::get(
        'suppliers/{supplier}/delete',
        [App\Http\Controllers\SupplierController::class,
            'delete'
        ])->name('suppliers.delete');
    Route::resource('suppliers', App\Http\Controllers\SupplierController::class);

    Route::prefix('configurations')->name('configurations.')->group(function () {
        Route::get('system', [SystemConfigurationController::class, 'edit'])->name('system.edit');
        Route::put('system', [SystemConfigurationController::class, 'update'])->name('system.update');
    });
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'code',
        'barcode',
        'name',
        'photo_url',
        'description',
        'price',
        'cost',
        'observation',
        'minimum_stock',
        'can_discount',
        'discount_percentage',
        'can_commission',
        'commission_percentage',
        'is_replacement',
        'is_new',
        'is_active',
        'type',
        'is_excl_serv'
    ];

    public function categories()
    {
       return $this->belongsToMany(Category::class, 'products_categories');
    }

    public function orders()
    {
        return $this->belongsToMany(Order::class);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use App\Models\Product;
use App\Services\Product\IndexProductService;
use App\Models\Category;

class ProductController extends Controller
{
    /**
     * @var IndexProductService
     */
    private $indexProductService;

    /**
     * ProductController constructor.
     * @param IndexProductService $indexProductService
     */
    public function __construct(IndexProductService $indexProductService)
    {
        $this->indexProductService = $indexProductService;
    }

    /**
     * Display a listing of the resource.
     * @param Request $request
     * @return Application|Factory|View
     */
    public function index(Request $request)
    {
        $search = null;
        if ($request->search) {
            $search = $request->search;
        }
        $products = $this->indexProductService->run($request);

        if ($request->expectsJson()) {
            return response($products);
        }
        return view('products.index')
            ->with('products', $products)
            ->with('search', $search);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $categories = Category::with('children')
                        ->where('parent_id', null)
                        ->get();

        return view('products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $user = auth()->user();

        if($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $fileName   = time() . '.' . $photo->getClientOriginalExtension();
            $data['photo_url'] = $photo->storeAs('public/products_photos', $fileName, 'local');
            $data['photo_url'] = str_replace('public/', '', $data['photo_url']);
        }

        $data['can_discount'] = isset($data['can_discount']) ? true : false;
        $data['can_commission'] = isset($data['can_commission']) ? true : false;
        $data['is_replacement'] = isset($data['is_replacement']) ? true : false;
        $data['is_new'] = isset($data['is_new']) ? true : false;
        $data['is_active'] = isset($data['is_active']) ? true : false;
        $data['is_excl_serv'] = isset($data['is_excl_serv']) ? true : false;

        $data['discount_percentage'] =
        $data['can_discount'] ?
        $data['discount_percentage'] : null;

        $data['commission_percentage'] =
        $data['can_commission'] ?
        $data['commission_percentage'] : null;

        $newProduct = new Product($data);

        $newProduct->user_add_id = $user->id;
        $newProduct->save();

        foreach($data['categories'] as $category) {
            $newProduct->categories()->attach($category);
        }


        return redirect()->route('products.index');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        $categories = Category::with('children')
                        ->where('parent_id', null)
                        ->get();
        $productCategories = $product->categories->modelKeys();

        return view('products.edit', compact('product', 'categories', 'productCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();
        $product = Product::findOrFail($id);

        if($request->hasFile('photo')) {
            $photo = $request->file('photo');
            $fileName   = time() . '.' . $photo->getClientOriginalExtension();
            $data['photo_url'] = $photo->storeAs('public/products_photos', $fileName, 'local');
            $data['photo_url'] = str_replace('public/', '', $data['photo_url']);
        }

        $data['can_discount'] = isset($data['can_discount']) ? true : false;
        $data['can_commission'] = isset($data['can_commission']) ? true : false;
        $data['is_replacement'] = isset($data['is_replacement']) ? true : false;
        $data['is_new'] = isset($data['is_new']) ? true : false;
        $data['is_active'] = isset($data['is_active']) ? true : false;
        $data['is_excl_serv'] = isset($data['is_excl_serv']) ? true : false;

        $data['discount_percentage'] =
        $data['can_discount'] ?
        $data['discount_percentage'] : null;

        $data['commission_percentage'] =
        $data['can_commission'] ?
        $data['commission_percentage'] : null;

        foreach($data['categories'] as $category) {
            $product->categories()->attach($category);
        }

        $product->update($data);

        return redirect()->route('products.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function delete($id)
    {

        $product = Product::findOrFail($id);

        return view('products.delete', compact('product'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Product::destroy($id);

        return redirect()->route('products.index');
    }
}

resources/views/products/create.blade.php
@extends('adminlte::page')

@section('title', 'Produtos')

@section('content_header')
    <h1>Produtos</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Cadastrar novo produto</h3>
          </div>
          <form method="POST" enctype="multipart/form-data" action="{{route('products.store')}}">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group">
                <label for="name">Nome do Produto</label>
                <input type="text" class="form-control" name="name" id="name">
              </div>
              <div class="form-group">
                <label for="photo">Foto</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" name="photo" id="photo">
                  <label class="custom-file-label" for="photo">Selecione um arquivo</label>
                </div>
              </div>
              <div class="form-group">
                <label>Categorias</label>
                <select id="categories" name="categories[]" class="select2" multiple="multiple" data-placeholder="Selecione as Categorias" style="width: 100%;">
                  @foreach ($categories as $category)
                    <option value="{{$category->id}}">{{$category->name}}</option>
                    @foreach ($category->children as $subcategory)
                        <option value="{{$subcategory->id}}"> -- {{$subcategory->name}}</option>
                    @endforeach
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label for="code">Código do Produto</label>
                <input type="text" class="form-control" name="code" id="code">
              </div>
              <div class="form-group">
                <label for="barcode">Código de Barra</label>
                <input type="text" class="form-control" name="barcode" id="barcode">
              </div>
              <div class="form-group">
                <label for="description">Descrição</label>
                <input type="text" class="form-control" name="description" id="description">
              </div>
              <div class="form-group">
                <label for="price">Valor</label>
                <input type="text" class="form-control" name="price" id="price">
              </div>
              <div class="form-group">
                <label for="cost">Custo</label>
                <input type="text" class="form-control" name="cost" id="cost">
              </div>
              <div class="form-group">
                <label for="observation">Observação</label>
                <input type="text" class="form-control" name="observation" id="observation">
              </div>
              <div class="form-group">
                <label for="minimum_stock">Estoque Minimo</label>
                <input type="text" class="form-control" name="minimum_stock" id="minimum_stock">
              </div>
              <div class="form-group">
                <label for="type">Tipo de Medida</label>
                <select name="type" id="type" class="form-control">
                    <option value="un">un</option>
                    <option value="kg">kg</option>
                    <option value="un">outro</option>
                </select>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="can_discount" name="can_discount">
                <label class="form-check-label" for="can_discount">Aceita Desconto?</label>
              </div>
              <div class="form-group" id="discount_input">
                <label for="discount_percentage">Porcentagem Máxima de Desconto</label>
                <input type="text" class="form-control" name="discount_percentage" id="discount_percentage">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="can_commission" name="can_commission">
                <label class="form-check-label" for="can_commission">Aceita Comissão?</label>
              </div>
              <div class="form-group" id="commission_input">
                <label for="commission_percentage">Porcentagem de Commisão</label>
                <input type="text" class="form-control" name="commission_percentage" id="commission_percentage">
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_replacement" name="is_replacement">
                <label class="form-check-label" for="is_replacement">É Reposição?</label>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_new" name="is_new">
                <label class="form-check-label" for="is_new">É Novo?</label>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_excl_serv" name="is_excl_serv">
                <label class="form-check-label" for="is_excl_serv">É Serviço Exclusivo?</label>
              </div>
              <div class="form-check">
                <input type="checkbox" class="form-check-input" id="is_active" name="is_active">
                <label class="form-check-label" for="is_active">Ativo?</label>
              </div>
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                <a href="{{route('products.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.bscustomfileinput', true)
@section('plugins.Select2', true)

@section('js')
<script>
    $(document).ready(function () {
        $('.select2').select2();
        bscustomfileinput.init();

    });

    $('#discount_input').hide();
    $('#commission_input').hide();

    $('#can_discount').click(function() {
        if($(this).is(':checked')) {
            $('#discount_input').show();
        } else {
            $('#discount_input').hide();
        }
    });

    $('#can_commission').click(function() {
        if($(this).is(':checked')) {
            $('#commission_input').show();
        } else {
            $('#commission_input').hide();
        }
    });
</script>
@stop

resources/views/products/delete.blade.php
@extends('adminlte::page')

@section('title', 'Produtos')

@section('content_header')
    <h1>Produtos</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Deletar Produto - {{$product->name}}</h3>
          </div>
          <form method="POST" action="{{route('products.destroy', ['product' => $product->id])}}">
            <!-- /.card-header -->
            <div class="card-body">
                Deseja realmente deletar a categoria - {{$product->name}}?
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                @method('delete')
                <a href="{{route('products.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('js')
@stop

resources/views/products/edit.blade.php
@extends('adminlte::page')

@section('title', 'Produtos')

@section('content_header')
    <h1>Produtos</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Editar produto - {{$product->name}}</h3>
          </div>
          <form method="POST" action="{{route('products.update', ['product' => $product->id])}}">
            <!-- /.card-header -->
            <div class="card-body">
              <div class="form-group">
                <label for="name">Nome do Produto</label>
                <input value="{{$product->name}}" type="text" class="form-control" name="name" id="name">
              </div>
              <div class="form-group">
                <label for="photo">Foto</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" name="photo" id="photo">
                  <label class="custom-file-label" for="photo">Selecione um arquivo</label>
                </div>
              </div>
              <div class="form-group">
                <label>Categorias</label>
                <select id="categories" name="categories[]" class="select2" multiple="multiple" data-placeholder="Selecione as Categorias" style="width: 100%;">
                  @foreach ($categories as $category)
                    <option selected="{{in_array($category->id, $productCategories)}}" value="{{$category->id}}">
                        {{$category->name}}
                    </option>
                    @foreach ($category->children as $subcategory)
                        <option selected="{{in_array($subcategory->id, $productCategories)}}" value="{{$subcategory->id}}">
                            -- {{$subcategory->name}}
                        </option>
                    @endforeach
                  @endforeach
                </select>
              </div>
              <div class="form-group">
                <label for="code">Código do Produto</label>
                <input value="{{$product->code}}" type="text" class="form-control" name="code" id="code">
              </div>
              <div class="form-group">
                <label for="barcode">Código de Barra</label>
                <input value="{{$product->barcode}}" type="text" class="form-control" name="barcode" id="barcode">
              </div>
              <div class="form-group">
                <label for="description">Descrição</label>
                <input value="{{$product->description}}" type="text" class="form-control" name="description" id="description">
              </div>
              <div class="form-group">
                <label for="price">Valor</label>
                <input value="{{$product->price}}" type="text" class="form-control" name="price" id="price">
              </div>
              <div class="form-group">
                <label for="cost">Custo</label>
                <input value="{{$product->cost}}" type="text" class="form-control" name="cost" id="cost">
              </div>
              <div class="form-group">
                <label for="observation">Observação</label>
                <input value="{{$product->observation}}" type="text" class="form-control" name="observation" id="observation">
              </div>
              <div class="form-group">
                <label for="minimum_stock">Estoque Minimo</label>
                <input value="{{$product->minimum_stock}}" type="text" class="form-control" name="minimum_stock" id="minimum_stock">
              </div>
              <div class="form-group">
                <label for="type">Tipo de Medida</label>
                <select value="{{$product->type}}" name="type" id="type" class="form-control">
                    <option value="un">un</option>
                    <option value="kg">kg</option>
                    <option value="un">outro</option>
                </select>
              </div>
              <div class="form-check">
                <input checked="{{$product->can_discount}}" type="checkbox" class="form-check-input" id="can_discount" name="can_discount">
                <label class="form-check-label" for="can_discount">Aceita Desconto?</label>
              </div>
              <div class="form-group" id="discount_input">
                <label for="discount_percentage">Porcentagem Máxima de Desconto</label>
                <input value="{{$product->discount_percentage}}" type="text" class="form-control" name="discount_percentage" id="discount_percentage">
              </div>
              <div class="form-check">
                <input checked="{{$product->can_commission}}" type="checkbox" class="form-check-input" id="can_commission" name="can_commission">
                <label class="form-check-label" for="can_commission">Aceita Comissão?</label>
              </div>
              <div class="form-group" id="commission_input">
                <label for="commission_percentage">Porcentagem de Commisão</label>
                <input value="{{$product->commission_percentage}}" type="text" class="form-control" name="commission_percentage" id="commission_percentage">
              </div>
              <div class="form-check">
                <input checked="{{$product->is_replacement}}" type="checkbox" class="form-check-input" id="is_replacement" name="is_replacement">
                <label class="form-check-label" for="is_replacement">É Reposição?</label>
              </div>
              <div class="form-check">
                <input checked="{{$product->is_new}}" type="checkbox" class="form-check-input" id="is_new" name="is_new">
                <label class="form-check-label" for="is_new">É Novo?</label>
              </div>
              <div class="form-check">
                <input checked="{{$product->is_excl_serv}}" type="checkbox" class="form-check-input" id="is_excl_serv" name="is_excl_serv">
                <label class="form-check-label" for="is_excl_serv">É Serviço Exclusivo?</label>
              </div>
              <div class="form-check">
                <input checked="{{$product->is_active}}" type="checkbox" class="form-check-input" id="is_active" name="is_active">
                <label class="form-check-label" for="is_active">Ativo?</label>
              </div>
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @method('put')
                @csrf
                <a href="{{route('products.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop
@section('plugins.bscustomfileinput', true)
@section('plugins.Select2', true)

@section('js')
<script>
    $(document).ready(function () {
        $('.select2').select2();
        bscustomfileinput.init();
    });

    if($('#can_discount').is(':checked')) {
        $('#discount_input').show();
    } else {
        $('#discount_input').hide();
    }

    if($('#can_commission').is(':checked')) {
        $('#commission_input').show();
    } else {
        $('#commission_input').hide();
    }

    $('#can_discount').click(function() {
        if($(this).is(':checked')) {
            $('#discount_input').show();
        } else {
            $('#discount_input').hide();
        }
    });

    $('#can_commission').click(function() {
        if($(this).is(':checked')) {
            $('#commission_input').show();
        } else {
            $('#commission_input').hide();
        }
    });
</script>
@stop

resources/views/products/index.blade.php
@extends('adminlte::page')

@section('title', 'Produtos')

@section('content_header')
    <h1>Produtos</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Lista de Produtos</h3>
            <div class="card-tools">
                <a href="{{route('products.create')}}">Cadastrar novo produto</a>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="users" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>ID</th>
                <th>Imagem</th>
                <th>Nome</th>
                <th>Ações</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($products as $product)
                  <tr>
                    <td>{{$product->id}}</td>
                    <td><img width="48" height="48" src="{{asset('storage/'.$product->photo_url)}}"></td>
                    <td>{{$product->name}}</td>
                    <td>
                        <a href="{{route('products.edit', ['product' => $product->id])}}">
                            <i class="mx-2 fas fa-pen"></i>
                        </a>
                        <a href="{{route('products.delete', ['product' => $product->id])}}">
                            <i class="mx-2 fas fa-trash"></i>
                        </a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('css')
    <link rel="stylesheet" href="/css/admin_custom.css">
@stop

@section('plugins.Datatables', true)

@section('js')
    <script>
    $(function () {
        $('#users').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": false,
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
        });
    });
    </script>
@stop