routes/web.php
<?php

use App\Http\Controllers\OrderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\SystemConfigurationController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::middleware(['auth'])->group(function () {
    Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home'); 

    Route::get(
        'categories/{category}/delete',
        [App\Http\Controllers\CategoryController::class,
            'delete'
        ])->name('categories.delete');
    Route::resource('categories', App\Http\Controllers\CategoryController::class);

    Route::get(
        'clients/{client}/delete',
        [App\Http\Controllers\ClientController::class,
            'delete'
        ])->name('clients.delete');
    Route::resource('clients', App\Http\Controllers\ClientController::class);

    Route::get(
        'users/{user}/delete',
        [App\Http\Controllers\UserController::class,
            'delete'
        ])->name('users.delete');
    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get(
        'products/{product}/delete',
        [App\Http\Controllers\ProductController::class,
            'delete'
        ])->name('products.delete');
    Route::resource('products', ProductController::class);

    Route::resource('orders', OrderController::class);
    Route::get('pdv', [OrderController::class, 'create']);

    Route::get(
        'suppliers/{supplier}/delete',
        [App\Http\Controllers\SupplierController::class,
            'delete'
        ])->name('suppliers.delete');
    Route::resource('suppliers', App\Http\Controllers\SupplierController::class);

    Route::prefix('configurations')->name('configurations.')->group(function () {
        Route::get('system', [SystemConfigurationController::class, 'edit'])->name('system.edit');
        Route::put('system', [SystemConfigurationController::class, 'update'])->name('system.update');
    });
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    use HasFactory, SoftDeletes;

    protected $fillable = [
        'name',
        'photo_url',
        'cnpj',
        'state_registration',
        'cellphone',
        'phone',
        'responsible_person',
        'observation',
    ];

    public function address()
    {
        return $this->morphOne(Address::class, 'owner');
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Services\Supplier\{
    IndexSupplierService,
    StoreSupplierService,
    UpdateSupplierService,
    DeleteSupplierService,
};
use App\Models\Supplier;
use App\Http\Requests\SupplierRequest;

class SupplierController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(IndexSupplierService $indexSupplierService)
    {
        $suppliers = $indexSupplierService->run();

        return view('suppliers.index', compact('suppliers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('suppliers.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\SupplierRequest  $supplierRequest
     * @param  \App\Services\StoreSupplierService  $storeSupplierService
     * @return \Illuminate\Http\Response
     */
    public function store(SupplierRequest $supplierRequest, StoreSupplierService $storeSupplierService)
    {
        $data = $supplierRequest->validated();
        $storeSupplierService->run($data);

        return redirect()->route('suppliers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Supplier $supplier)
    {
        return view('suppliers.edit', compact('supplier'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(SupplierRequest $supplierRequest, UpdateSupplierService $updateSupplierService, Supplier $supplier)
    {
        $data = $supplierRequest->validated();

        $updateSupplierService->run($supplier, $data);

        return redirect()->route('suppliers.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function delete(DeleteSupplierService $deleteSupplierSevice, Supplier $supplier)
    {
        return view('suppliers.delete', compact('supplier'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(DeleteSupplierService $deleteSupplierSevice, Supplier $supplier)
    {
        $deleteSupplierSevice->run($supplier);

        return redirect()->route('suppliers.index');
    }
}

resources/views/suppliers/create.blade.php
@extends('adminlte::page')

@section('title', 'Fornecedores')

@section('content_header')
    <h1>Fornecedores</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Cadastrar Novo Fornecedor</h3>
          </div>
          <form method="POST" enctype="multipart/form-data" action="/suppliers">
            <!-- /.card-header -->
            <div class="card-body">
                <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
                </ul>
              <div class="form-group">
                <label for="name">Nome</label>
                <input type="text" class="form-control" name="name" id="name">
              </div>
              <div class="form-group">
                <label for="photo">Foto</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" name="photo" id="photo">
                  <label class="custom-file-label" for="photo">Selecione um arquivo</label>
                </div>
              </div>
              <div class="form-group">
                  <label for="cnpj">CNPJ</label>
                  <input data-inputmask="'mask': '99.999.999/9999-99'" type="text" class="form-control" name="cnpj" id="cpnj">
              </div>
              <div class="form-group">
                  <label for="state_registration">Inscrição Estadual</label>
                  <input  data-inputmask="'mask': '999.999.999.999'" type="text" class="form-control" name="state_registration" id="state_registration">
              </div>
              <div class="form-group">
                  <label for="cellphone">Celular</label>
                  <input data-inputmask="'mask': '(99) 99999-9999'" type="text" class="form-control" name="cellphone" id="cellphone">
              </div>
              <div class="form-group">
                  <label for="phone">Telefone</label>
                  <input data-inputmask="'mask': '(99) 9999-9999'" type="text" class="form-control" name="phone" id="phone">
              </div>
              <div class="form-group">
                  <label for="responsible_person">Responsável</label>
                  <input type="text" class="form-control" name="responsible_person" id="resonsible_person">
              </div>
              <div class="form-group">
                  <label for="observation">Observação</label>
                  <input type="text" class="form-control" name="observation" id="observation">
              </div>
              <h5 class="mt-2">Endereço</h5>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="postcode">CEP</label>
                  <input data-inputmask="'mask': '99999-999'" type="text" class="form-control" name="postcode" id="postcode">
                </div>
                <div class="form-group col-md-6">
                  <label for="street">Rua/Av.</label>
                  <input type="text" class="form-control" name="street" id="street">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="neighborhood">Bairro</label>
                  <input type="text" class="form-control" name="neighborhood" id="neighborhood">
                </div>
                <div class="form-group col-md-3">
                  <label for="number">Numero</label>
                  <input type="text" class="form-control" name="number" id="number">
                </div>
                <div class="form-group col-md-3">
                  <label for="complement">Complemento (Opcional)</label>
                  <input type="text" class="form-control" name="complement" id="complement">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="city">Cidade</label>
                  <input type="text" class="form-control" name="city" id="city">
                </div>
                <div class="form-group col-md-6">
                    <label for="state">Estado</label>
                    <select name="state" id="state" class="form-control">
                        @include('utils.states')
                    </select>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                <a href="{{route('clients.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.bscustomfileinput', true)
@section('plugins.InputMask', true)

@section('js')
<script>
    $(document).ready(function () {
        bscustomfileinput.init();
    });

    $(":input").inputmask();
    $("#postcode").blur(function() {
         var postcode = $(this).val().replace(/\D/g, '');
         console.log(postcode)
        if (postcode.length === 8) {
            $("#street").val("...");
            $("#neighborhood").val("...");
            $("#city").val("...");
            $("#state").val("...");

            $.getJSON("https://viacep.com.br/ws/"+ postcode +"/json/?callback=?", function(data) {
                console.log(data)
                if (!("erro" in data)) {
                    $("#street").val(data.logradouro);
                    $("#neighborhood").val(data.bairro);
                    $("#city").val(data.localidade);
                    $("#state").val(data.uf);
                }
            });
        }
    });

</script>
@stop

resources/views/suppliers/delete.blade.php
@extends('adminlte::page')

@section('title', 'Fornecedores')

@section('content_header')
    <h1>Fornecedores</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Deletar Fornecedor - {{$supplier->name}}</h3>
          </div>
          <form method="POST" action="{{route('suppliers.destroy', ['supplier' => $supplier->id])}}">
            <!-- /.card-header -->
            <div class="card-body">
                Deseja realmente deletar o fornecedor - {{$supplier->name}}?
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                @method('delete')
                <a href="{{route('clients.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('js')
@stop

resources/views/suppliers/edit.blade.php
@extends('adminlte::page')

@section('title', 'Fornecedores')

@section('content_header')
    <h1>Fornecedores</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Editar Fornecedor - {{$supplier->name}}</h3>
          </div>
          <form method="POST" enctype="multipart/form-data" action="{{route('suppliers.update', ['supplier' => $supplier->id])}}">
            @method('put')
            <!-- /.card-header -->
            <div class="card-body">
              <ul>
              @foreach ($errors->all() as $error)
                  <li>{{ $error }}</li>
              @endforeach
              </ul>
              <div class="form-group">
                <label for="name">Nome</label>
                <input value="{{$supplier->name}}" type="text" class="form-control" name="name" id="name">
              </div>
              <div class="form-group">
                <label for="photo">Foto</label>
                <div class="custom-file">
                  <input type="file" class="custom-file-input" name="photo" id="photo">
                  <label class="custom-file-label" for="photo">Selecione um arquivo</label>
                </div>
              </div>
              <div class="form-group">
                  <label for="cnpj">CNPJ</label>
                  <input value="{{$supplier->cnpj}}" data-inputmask="'mask': '99.999.999/9999-99'" type="text" class="form-control" name="cnpj" id="cpnj">
              </div>
              <div class="form-group">
                  <label for="state_registration">Inscrição Estadual</label>
                  <input value="{{$supplier->state_registration}}" data-inputmask="'mask': '999.999.999.999'" type="text" class="form-control" name="state_registration" id="state_registration">
              </div>
              <div class="form-group">
                  <label for="cellphone">Celular</label>
                  <input value="{{$supplier->cellphone}}" data-inputmask="'mask': '(99) 99999-9999'" type="text" class="form-control" name="cellphone" id="cellphone">
              </div>
              <div class="form-group">
                  <label for="phone">Telefone</label>
                  <input value="{{$supplier->phone}}" data-inputmask="'mask': '(99) 9999-9999'" type="text" class="form-control" name="phone" id="phone">
              </div>
              <div class="form-group">
                  <label for="responsible_person">Responsável</label>
                  <input value="{{$supplier->responsible_person}}" type="text" class="form-control" name="responsible_person" id="resonsible_person">
              </div>
              <div class="form-group">
                  <label for="observation">Observação</label>
                  <input value="{{$supplier->observation}}" type="text" class="form-control" name="observation" id="observation">
              </div>
              <h5 class="mt-2">Endereço</h5>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="postcode">CEP</label>
                  <input value="{{$supplier->address->postcode}}" data-inputmask="'mask': '99999-999'" type="text" class="form-control" name="postcode" id="postcode">
                </div>
                <div class="form-group col-md-6">
                  <label for="street">Rua/Av.</label>
                  <input value="{{$supplier->address->street}}" type="text" class="form-control" name="street" id="street">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="neighborhood">Bairro</label>
                  <input value="{{$supplier->address->neighborhood}}" type="text" class="form-control" name="neighborhood" id="neighborhood">
                </div>
                <div class="form-group col-md-3">
                  <label for="number">Numero</label>
                  <input value="{{$supplier->address->number}}" type="text" class="form-control" name="number" id="number">
                </div>
                <div class="form-group col-md-3">
                  <label for="complement">Complemento (Opcional)</label>
                  <input value="{{$supplier->address->complement}}" type="text" class="form-control" name="complement" id="complement">
                </div>
              </div>
              <div class="row">
                <div class="form-group col-md-6">
                  <label for="city">Cidade</label>
                  <input value="{{$supplier->address->city}}" type="text" class="form-control" name="city" id="city">
                </div>
                <div class="form-group col-md-6">
                    <label for="state">Estado</label>
                    <select value="{{$supplier->address->state}}" name="state" id="state" class="form-control">
                        @include('utils.states')
                    </select>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <div class="card-footer">
                @csrf
                <a href="{{route('clients.index')}}" class="btn btn-primary">Cancelar</a>
                <button type="submit" class="btn btn-primary">Confirmar</button>
            </div>
        </form>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.bscustomfileinput', true)
@section('plugins.InputMask', true)

@section('js')
<script>
    $(document).ready(function () {
        bscustomfileinput.init();
    });

    $(":input").inputmask();
    $("#postcode").blur(function() {
         var postcode = $(this).val().replace(/\D/g, '');
         console.log(postcode)
        if (postcode.length === 8) {
            $("#street").val("...");
            $("#neighborhood").val("...");
            $("#city").val("...");
            $("#state").val("...");

            $.getJSON("https://viacep.com.br/ws/"+ postcode +"/json/?callback=?", function(data) {
                console.log(data)
                if (!("erro" in data)) {
                    $("#street").val(data.logradouro);
                    $("#neighborhood").val(data.bairro);
                    $("#city").val(data.localidade);
                    $("#state").val(data.uf);
                }
            });
        }
    });

</script>
@stop

resources/views/suppliers/index.blade.php
@extends('adminlte::page')

@section('title', 'Fornecedores')

@section('content_header')
    <h1>Fornecedores</h1>
@stop

@section('content')
<div class="container-fluid">
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-header">
            <h3 class="card-title">Lista de Fornecedores</h3>
            <div class="card-tools">
                <a href="{{route('suppliers.create')}}">Cadastrar Novo Fornecedor</a>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body">
            <table id="suppliers" class="table table-bordered table-hover">
              <thead>
              <tr>
                <th>ID</th>
                <th>Imagem</th>
                <th>Nome</th>
                <th>Responsável</th>
                <th>Ações</th>
              </tr>
              </thead>
              <tbody>
                @foreach ($suppliers as $supplier)
                  <tr>
                    <td>{{$supplier->id}}</td>
                    <td><img width="48" height="48" src="{{asset('storage/'.$supplier->photo_url)}}"></td>
                    <td>{{$supplier->name}}</td>
                    <td>{{$supplier->responsible_person}}</td>
                    <td>
                        <a href="{{route('suppliers.edit', ['supplier' => $supplier->id])}}">
                            <i class="mx-2 fas fa-pen"></i>
                        </a>
                        <a href="{{route('suppliers.delete', ['supplier' => $supplier->id])}}">
                            <i class="mx-2 fas fa-trash"></i>
                        </a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
          <!-- /.card-body -->
        </div>
        <!-- /.card -->
      </div>
    </div>
</div>
@stop

@section('plugins.Datatables', true)

@section('js')
    <script>
    $(function () {
        $('#suppliers').DataTable({
        "paging": true,
        "lengthChange": false,
        "searching": true,
        "language": {
            search: 'Pesquisar'
        },
        "ordering": true,
        "info": true,
        "autoWidth": false,
        "responsive": true,
        });
    });
    </script>
@stop